#!/usr/bin/env python3

import json
import sys

from pathlib import Path

if __name__ == "__main__":
    # Parse a CMake file API response for codemodel-v2
    # to extract the name of the library or executable
    # generated by the build process,
    # and to determine whether it is an executable.

    # The response is generated when the empty file
    # ".cmake/api/v1/query/codemodel-v2"
    # exists in the working directory when cmake is invoked.

    # Takes two arguments:
    # 1. A path to the directory cmake was invoked from (containing .cmake)
    # 2. "name" or "type", determining which field to print for the build target

    build_root = Path(sys.argv[1])
    cmake_reply_root = build_root / ".cmake" / "api" / "v1" / "reply"

    # load index of response
    index_path = tuple(cmake_reply_root.glob("index-*.json"))[0]
    with open(index_path, "r") as f:
        index = json.load(f)

    # load codemodel reply
    codemodel_filename = index["reply"]["codemodel-v2"]["jsonFile"]
    codemodel_path = cmake_reply_root / codemodel_filename
    with open(codemodel_path, "r") as f:
        codemodel = json.load(f)

    # assume one translated build configuration and one target (for now)
    target_filename = codemodel["configurations"][0]["targets"][0]["jsonFile"]
    target_path = cmake_reply_root / target_filename
    with open(target_path, "r") as f:
        target = json.load(f)

    # Extract name or type of target
    # If "type", the result will be "EXECUTABLE" or "<something>_LIBRARY"
    print(target[sys.argv[2]])
    target_type = target["type"]
