# File generated by CompCert 3.14
# Command line: -S -fpacked-structs -fstruct-passing -funstructured-switch -std=c18 -L/private/tmp/compcert-rust-cns/runtime -lm -rust-edition 2024 -Xpreprocessor -arch -Xpreprocessor arm64 -Xpreprocessor -U__clang__ -Xpreprocessor -U__BLOCKS__ -Xpreprocessor -D__attribute__(x)= -Xpreprocessor -D__asm(x)= -Xpreprocessor -D_Nullable= -Xpreprocessor -D_Nonnull= -Xpreprocessor -D__DARWIN_OS_INLINE=static inline -Xpreprocessor -Wno-#warnings -Xpreprocessor -D__uint128_t=unsigned long long -drustlight switch.c
	.text
	.align	16
	.globl switch_val
switch_val:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	cmpl	$1, %edi
	je	.L100
	cmpl	$2, %edi
	jne	.L101
	movl	$4, %eax
	jmp	.L102
.L101:
	leal	1(%edi), %eax
	jmp	.L102
.L100:
	movl	$2, %eax
.L102:
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	switch_val, @function
	.size	switch_val, . - switch_val
