edition := "2021"

test: build
    pushd rust_project && cargo test && popd

build: clean
    ccomp -fpacked-structs -fstruct-passing -funstructured-switch -std=c18 -drustlight -L../../runtime/ -lm -rust-edition {{ edition }} *.c
    mkdir -p rust_project/tests
    cp *.rs rust_project/tests/

clean:
    rm -rf rust_project
