# File generated by CompCert 3.14
# Command line: -S -fpacked-structs -fstruct-passing -funstructured-switch -std=c18 -L/private/tmp/compcert-rust-cns/runtime -lm -rust-edition 2024 -Xpreprocessor -arch -Xpreprocessor arm64 -Xpreprocessor -U__clang__ -Xpreprocessor -U__BLOCKS__ -Xpreprocessor -D__attribute__(x)= -Xpreprocessor -D__asm(x)= -Xpreprocessor -D_Nullable= -Xpreprocessor -D_Nonnull= -Xpreprocessor -D__DARWIN_OS_INLINE=static inline -Xpreprocessor -Wno-#warnings -Xpreprocessor -D__uint128_t=unsigned long long -drustlight irreducible.c
	.text
	.align	16
	.globl irreducible
irreducible:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
.L100:
	cmpl	$6, %edi
	jge	.L101
	leal	1(%edi), %edi
	jmp	.L102
.L101:
	cmpl	$9, %edi
	jge	.L102
	leal	2(%edi), %edi
	jmp	.L100
.L102:
	cmpl	$20, %edi
	jge	.L103
	leal	90(%edi), %edi
	jmp	.L101
.L103:
	movq	%rdi, %rax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	irreducible, @function
	.size	irreducible, . - irreducible
